name = "gibbshierarchical"
uuid = "db23c552-c472-4c6c-b1e0-ffe581ef02d6"
authors = ["alicechevaux"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
